### ISSUE TITLE
Use of HttpClientFactory instead of HttpClient?

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-delivery-sdk-net#182]
### Motivation

In viewing some of the performance best practices document I had noticed awhile back you are using a single httpClient for all Kentico Kontent requests.

According to this you should instead use HttpClientFactory:

https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1#pool-http-connections-with-httpclientfactory

It's not entirely clear to me though if this guidance applies to a static httpClient like what all of your examples use. 

### Proposed solution

Determine if a static HttpClient is OK or if it is better to use HttpClientFactory.

### Additional context

N/A

**Comment by petrsvihlik** [comment]
Hi @xantari ,
you made a brilliant point!

## Motivation

First, to answer your concerns and address the two problems with the `HttpClient` described in [MS docs](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net-core):

1. **Performance (aka socket depletion)**: the `DeliveryClient` (re)uses a single instance of `HttpClient` over and over again. Although the `HttpClient` implements `IDisposlable` and thus suggests repeated instantiation, it's not designed to be short-lived. So, performance-wise, the Delivery SDK acts according to the best practice and shouldn't pose an issue.
2. **Disrespecting DNS changes**: This is a [global problem of .NET](https://github.com/dotnet/corefx/issues/11224) which could previously be worked around by using the `ServicePointManager`. The [current best practice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#httpclient-lifetimes) is to use the `HttpClientFactory` and `.SetHandlerLifetime(...)`.

So, generally speaking, using the Delivery SDK as-is is safe. However, if you wish to use the `HttpClientFactory` with the Kontent's Delivery SDK, you need to use the `Generated clients` approach described in the [MS docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#generated-clients):

## DeliveryClient + HttpClientFactory
```csharp
services.AddHttpClient("FactoryClient", c => c.DefaultRequestHeaders.Add("X-KC-SOURCE", "Greetings from the HttpClientFactory!")) // Or any other additional configuration
        .AddTypedClient(c => DeliveryClientBuilder.WithProjectId("975bf280-fd91-488c-994c-2f04416e5ee3").WithHttpClient(c).Build())
        .AddPolicyHandler(GetRetryPolicy()); // Add retry policies, etc.
```
Using the `HttpClientFactory` has some additional benefits, e.g. you get free logging, as @shanselman [demonstrates in his post](https://www.hanselman.com/blog/HttpClientFactoryForTypedHttpClientInstancesInASPNETCore21.aspx).

## Outstanding issues
Although it's possible to use `HttpClientFactory` with this SDK, I'll leave this issue open as I think we should improve several things:
- Add support for [`Named clients` and `Typed clients`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#consumption-patterns) - this is currently not possible which effectively prevents simultaneous usage of DI and multiple instances of the HttpClientFactory-powered `DeliveryClient` 
  - The [`WithHttpClient`](https://github.com/Kentico/kontent-delivery-sdk-net/blob/f4bcf86ff33fb17bb140b8fd8a54cd41f7098240/Kentico.Kontent.Delivery/Builders/DeliveryClient/DeliveryClientBuilderImplementation.cs#L37) should be replaced or accompanied by a method that would allow injection of the `HttpClientFactory`
    - This would be also useful for unit testing when injecting fake instances of the `HttpClient`
  - Use the `HttpClientFactory` internally for creating a default `HttpClient` instance when registering the [default dependencies](https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery/Extensions/ServiceCollectionExtensions.cs#L110)
  - Update the best practices on the [`DeliveryClient` instantiation](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Instantiating-DeliveryClient-with-Configuration-API-and-DI-in-ASP.NET-Core-MVC-apps)
- Refactor the resiliency policy
  - Make the [resiliency logic](https://github.com/Kentico/kontent-delivery-sdk-net/tree/master/Kentico.Kontent.Delivery/RetryPolicy) compatible with Polly, following the [best practices](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly) from MS docs
  - Add [Simmy](http://www.thepollyproject.org/2019/06/27/simmy-the-monkey-for-making-chaos/) for tests
  - Rewrite the [best practices](https://github.com/Kentico/kontent-delivery-sdk-net#retry-capabilities) on how to use the retry policy, favoring the usage of the `HttpClientFactory` in combination with `.AddPolicyHandler(...)` rather than handling it [internally](https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery/DeliveryClient.cs#L477)

We are currently working on best practices for .NET developers. We'll make sure to incorporate these learnings. (ping @tomasjurasek)

## Recommended extra reading:
- [HTTPCLIENTFACTORY IN ASP.NET CORE 2.1](https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore) by @stevejgordon
- [You're (probably still) using HttpClient wrong and it is destabilizing your software](https://josefottosson.se/you-are-probably-still-using-httpclient-wrong-and-it-is-destabilizing-your-software/) by @joseftw
  - [code](https://github.com/joseftw/jos.httpclient/tree/develop/src)
- [HttpClientFactoryServiceCollectionExtensions](https://github.com/aspnet/HttpClientFactory/blob/master/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs) to see the various ways of HttpClient registration

I hope this answer will help you and thanks again for pointing this out!

**Comment by petrsvihlik** [comment]
@xantari just to let you know - we're working on a new version that'll be optimized for usage together with the HttpClientFactory

**Comment by xantari** [comment]
@petrsvihlik great!

**Comment by petrsvihlik** [comment]
this will be a part of the v13 release. the docs will be taken care of separately.

 -> closing
