### ISSUE TITLE
Allow to instantiate an instance of a generated class

### ISSUE THREAD

**Issue by t-ben** [Kentico/kontent-delivery-sdk-net#235]
I am trying to instantiate an instance of one of  the classes generated by Kentico.Kontent.ModelGenerator.
I need that instance for my unit testing.
looked at the sdk tests for inspiration - Dev\Kentico\kontent-delivery-sdk-net\Kentico.Kontent.Delivery.Tests\DeliveryClientTests.cs
and in that test the code is hydrating a model. but when i try to build that code in my unit test it cannot create a new ModelProvider because its an internal class.
my product is Kentico Kontent (not Kentico).

sdk version 12.3.0 (i also looked at version 13.0.2 and i have the same problem there)
the code im trying to run is from function InitializeDeliveryClientWithACustomTypeProvider
as i need a client with a ModelProvider in order to hydrate the model as done in this test: 
DeliveryClientTests -> AssetPropertiesNotEmpty()
that is based on function InitializeDeliveryClientWithACustomTypeProvider

so far i was able to create a fake client based on test: kontent-delivery-sdk-net\Kentico.Kontent.Delivery.Tests\FakeHttpClientTests.cs
and although this fake client does return a content result with the json result - that wont cast correctly to the generated class model (var model = item.CastTo<Contentblock>();) since the properties of the model are coming out null.

please help me figure out is there a way to instantiate a fake model of a generated content type model ?

**Comment by petrsvihlik** [comment]
Hi @t-ben ,
I can see a lot of confusion. Let me break it down to smaller pieces and answer question by question.

**Prerequisites:**

1. We support only the latest version of the SDK, so please upgrade to 13.0.2 so that we can be of further help. If you have trouble upgrading, let us know in this thread - I'm sure we can resolve it.
2. If you're really keen on testing, I'd recommend upgrading straight to 14.0.0-rc3 (Check out the improvements we've done to make unit testing easier in the [rc1 release notes](https://github.com/Kentico/kontent-delivery-sdk-net/releases/tag/14.0.0-rc1). Especially #216.)
3. It would be very helpful if you could share your code to demonstrate the issues next time.

**Questions:**
1. Instantiating classes generated by Kentico.Kontent.ModelGenerator - all the generated models have a default public constructor so you can just call `var m = new MyModel();` (but I presume this is not what you're looking for)
2. I guess, what you're trying to do is to validate whether the DeliveryClient returns correct data. To do that, you need to fake the responses. There are three ways to do it:
  a. You can either fake the underlying HTTP layer and provide fake JSON files. See the [docs](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Faking-responses) and a [working example](https://github.com/Kentico/kontent-sample-app-net/blob/master/DancingGoat.Tests/ArticlesControllerTests.cs)
  b. Or you can create a repository layer on top of the DeliveryClient and test that. See the [example](https://github.com/Kentico/kontent-sample-app-net/blob/master/DancingGoat.Tests/CafesControllerTests.cs)
  c. Or finally, with v14, you can fake the `Delivery*Response` objects since they're abstracted as interfaces in `Kentico.Kontent.Delivery.Abstractions` (so you can use approach described in #216)
  There is no need to create instances of `ModelProvider` and other instances of internal classes required by the DeliveryClient. The only thing that you really need during the instantiation of the DeliveryClient is an implementation of `ITypeProvider` which is also generated by the model generator and which can also be faked by the way.

Hope this helps. Please let us know if it worked for you :)

**Comment by t-ben** [comment]
petrsvihlik thanks for your response.
version - I was asked by my architect to work on 12.3.0 I will have to check with him if its possible to move to 13.0.2.
Instantiating classes generated by Kentico.Kontent.ModelGenerator - here is an example of a test: 

the test gets a model instance from Kentico Delivery client:
[TestMethod]
        public async Task Client_Gets_A_Text_ContentBlock()
        {
            var response = await _client.GetItemAsync<KK.ContentBlock>("test_text_contentblock");
            var textBlock = response.Item;
            Assert.IsNotNull(textBlock);
            Assert.AreEqual(textBlock.ContentTypeContentBlockEnumContenttype.FirstOrDefault().Name, UiKit.Enums.ContentBlockEnum.ShowText.ToString());
            Assert.IsNotNull(textBlock.Contentconfig.FirstOrDefault());
            var config = (KK.TextContent)textBlock.Contentconfig.FirstOrDefault();
            Assert.AreEqual(config.BaseContentBlockClasses, "text-bold");
            Assert.AreEqual(config.BaseContentBlockId, "text-123");
            Assert.AreEqual(config.Text, "Hello World");
            Assert.AreEqual(config.WrapperTextWrapperEnumWrapper.FirstOrDefault().Name, UiKit.Enums.TextWrapperEnum.h1.ToString());
        }

what i was asking is - is there a way to instantiate a model without reading actual content from the delivery client. Fake that model as if the client returned it, having set all properties of the model and linked items etc.

thanks for your help
Tal.

**Comment by petrsvihlik** [comment]
If the goal is to avoid communicating with an external service, then you'll be good with the solution `a`:
>  a. You can either fake the underlying HTTP layer and provide fake JSON files. See the [docs](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Faking-responses) and a [working example](https://github.com/Kentico/kontent-sample-app-net/blob/master/DancingGoat.Tests/ArticlesControllerTests.cs)

You can store your immutable test fixtures in files or in the code and have your tests rely on them. This solution still uses the `DeliveryClient`, however, its HTTP client reads the JSON responses from your local files rather than from Kentico Kontent.

If the goal is to avoid using the `DeliveryClient` or to set up the models by hand, then the solution `c` is best for you:
> c. Or finally, with v14, you can fake the `Delivery*Response` objects since they're abstracted as interfaces in `Kentico.Kontent.Delivery.Abstractions` (so you can use the approach described in #216)

As all the returned types in v14 are interfaces, you can create specific implementations of virtually any type that the SDK outputs. Or, you can use your favorite mocking framework (we use e.g. Moq or FakeItEasy) to reduce the required manual work upfront.

The solution `b` is somewhere in between. You can benefit from the approach `c` without the need of upgrading to v14. It does, however, add extra complexity when you introduce the repository pattern.
> b. Or you can create a repository layer on top of the DeliveryClient and test that. See the [example](https://github.com/Kentico/kontent-sample-app-net/blob/master/DancingGoat.Tests/CafesControllerTests.cs)

**Comment by t-ben** [comment]
thanks for your direction.
as for option a. I explored the example and it works, but in order to produce an exact full response (include System and other Item props ) the client needs a ModelProvider instance. that cannot be created.
I appreciate your response and will see if we can use v14.

**Comment by petrsvihlik** [comment]
no matter whether you use `DeliveryClientBuilder` or `services.AddDeliveryClient` to get your client, it'll always have an instance of the `ModelProvider` registered. the SDK registers default dependencies if you don't register your own.
