### ISSUE TITLE
SDK Performance degradation from 13 - 15

### ISSUE THREAD

**Issue by johnhydemtm365** [Kentico/kontent-delivery-sdk-net#270]
### Brief bug description

What went wrong?
Upgraded to 15.0.0-rc1 and noticed a large performance impact with linked items where they are now extracted before as they are added at construction time when creating the DeliveryItemListingResponse class.

History: compared latest commit to commit 03/01/2020
In the old delivery client, DeliveryItemListingResponse,  Linked items used to be a dynamic property linked to a lazy object.
`_linkedItems = new Lazy<JObject>(() => (JObject)_response.Content["modular_content"].DeepClone(), LazyThreadSafetyMode.PublicationOnly);
`
Which was only actioned if the property was accessed.

However, in the new instance, this is populated when the content is returned inside the delivery client. I feel this is causing the issue. In the past, we have never used linked Items, well not intentionally anyway.....

### Expected behavior
To be honest I am not quite sure I fully understand the linked items part, as I have never intentionally used that property. Happy to discuss though...

As per email through to Martin, we have happened on this by chance by the way our content is structured for menu's.

**Comment by tomasjurasek** [comment]
Hi @johnhydemtm365,
thanks for reporting the issue. You are right, the problem is with a large amount of strongly-typed LinkedItems. We did a hotfix [15.0.0-rc2](https://www.nuget.org/packages/Kentico.Kontent.Delivery/15.0.0-rc2), where we have removed strongly-typed LinkedItems and added the dynamic LinkedItems for now.

Before releasing a stable version of 15th, we want to find a better solution for LinkedItems.

**Comment by petrsvihlik** [comment]
internal ref: DEL-2832

**Comment by Simply007** [comment]
We have decided to remove `LinkedItems` property from the response and added a wiki section describing the approach of mapping modular content to the strongly typed models in the [wiki page](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Retrieve-modular-content-from-API-response).

These changes are in [15.0.0-rc3](https://github.com/Kentico/kontent-delivery-sdk-net/releases/tag/15.0.0-rc3

**Comment by johnhydemtm365** [comment]
Hi, when are you guys releasing the next non release candidate?

**Comment by Simply007** [comment]
> Hi, when are you guys releasing the next non release candidate?

Hey @johnhydemtm365, I am planning to keep the RC for testing and evaluation for a couple of weeks. Don't quote me on that, but July/August is a realistic estimate to release the final candidate if nothing comes up.

I don't want to release them because of vacation and keeping the testing period. Would you be able to test it out? Or is there anything you would need to test it?

**Comment by johnhydemtm365** [comment]
Hi, we can update and test with the other stuff we have going on.
