### ISSUE TITLE
Pagination Class is not Serializable

### ISSUE THREAD

**Issue by johnhydemtm365** [Kentico/kontent-delivery-sdk-net#285]
### Brief bug description

What went wrong?
We are caching content responses, DeliveryItemListingResponse, and we noticed that when using paging, the value returned from cache did not have all the paging information so the front end did not know there was more pages.

Looking at this class:
https://github.com/Kentico/kontent-delivery-sdk-net/blob/c48f1a5133834af6d16c2e6a8e16c42d3a2a3a7c/Kentico.Kontent.Delivery/SharedModels/Pagination.cs#L9

It seems like the issue is the parameters....on the constructor do not match the original properties that will be used to serilaize the object

### Repro steps
Cache a paginated response from the delivery client

### Expected behavior
It caches correctly.

### Screenshots
![DeliveryClientCacheIssue](https://user-images.githubusercontent.com/32865335/137864667-e818ad74-f3b9-4d9c-87a8-da88d26bd1bb.PNG)

**Comment by Simply007** [comment]
Hello @johnhydemtm365,

thanks for the issue. I think you might be right according to [this discussion](https://stackoverflow.com/a/23017892/3529135).

If this is the root cause, the fix might be pretty simple, but I would like to cover this scenario with the test first.

Would you be willing to share the code snippet of your caching logic, so that we can get as close to your use case as possible and ideally verify that this is the root cause by unit test, and then fixing it? 

Another question - what version of the SDK you are using?

And also, since the repo is OS, we would be more than happy to review and accept a pull request with the fix. This could potentially speed up the fix itself.

**Comment by johnhydemtm365** [comment]
I have created a PR here:
https://github.com/Kentico/kontent-delivery-sdk-net/pull/286

**Comment by Simply007** [comment]
The final v15 version was released: https://www.nuget.org/packages/Kentico.Kontent.Delivery/15.0.1

The complete fix for #292 will be covered in a future versions.
