### ISSUE TITLE
.NET 6 Linked Content not populated

### ISSUE THREAD

**Issue by ClaytonHunt** [Kentico/kontent-delivery-sdk-net#297]
### Brief bug description
In a .NET 6 API, Linked Items are returning as null

### Repro steps
1. Add code to create delivery client
2. Request a page
3. Look at Sections property, it will be an Enumerable with the correct number of elements, but all the elements are null

### Expected behavior

I would expect Sections to be filled with the linked content objects.

### Test environment

 - Platform/OS: Windows, .NET 6
 - Browser: N/A
 - Version: 15.0.1

### Additional context

I found this error in a .NET 6 Blazor WASM Hosted project I have started working on

### Screenshots

![image](https://user-images.githubusercontent.com/1760277/140411171-26079848-64a6-4804-8a67-6f1ec3b6a0ad.png)
![image](https://user-images.githubusercontent.com/1760277/140411248-67c35bf4-f429-4502-baee-683eea1ebca9.png)

**Comment by Simply007** [comment]
Hello @ClaytonHunt,

thanks for reaching out. Actually, we are just validating moving from `netstandard 2.0` which the SDK currently targets to `net 6` (draft in #296) since .NET is about to be released next week. 

But this change requires a new major release if we want to be strict since "Support for older frameworks is being dropped, including frameworks older than .NET Framework 4.6.1, .NET Core 3.1, and .NET Standard 2.0", SO if we decide to make this change, we will include official .NET 6 support in version 16.

---

I guess you have scaffolded the app using `dotnet new blazorwasm` right?

May I also ask for a specific .NET SDK version you are using? 

This would help us to create a replicable environment and try to identify the root cause. Or, if you are willing to, you could try the [Source Link for debuugin](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Using-Source-Link-for-debugging) directly from your project.

---

Assuming the number of sections being returned (13) is correct. My guess is the SDKs does not know the actual type mapping for codename of a type<->model since there is no [Type provider registered](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Working-with-Strongly-Typed-Models#customizing-the-strong-type-binding-logic).

Could you test out registering the type provider? You can also generate one by `withtypeprovider` argument using `Kentico.Kontent.ModelGenerator` utility.

**Comment by ClaytonHunt** [comment]
Thanks for responding. My .NET 6 framework version is: 6.0.100-rc.2.21505.57

I think I have a solution working now. I was missing the ```WithTypeProvider``` in the ```DeliveryClientBuilder``` configuration. It would be a separate Issue, but just as a heads up for your .NET 6 updates:

I get the following error when using an injected IDeliveryClient
![image](https://user-images.githubusercontent.com/1760277/140503136-feb617e6-5a89-4ce6-a4f1-ed63c1004ef9.png)

Again, I can get the code working and look forward to updating to the latest Kentico version when it is ready for .NET 6
