### ISSUE TITLE
Cannot use MemoryCacheManager 

### ISSUE THREAD

**Issue by Enngage** [Kentico/kontent-delivery-sdk-net#313]
### Brief bug description

There is an example in https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Caching-responses#usage-without-di which suggest to use `DeliveryClientCache` but we can't do that because that class is marked as `internal`. 

`var cachedClient = new DeliveryClientCache(new MemoryCacheManager(new MemoryCache(memoryOptions), cacheOptions), client);`

### Expected behavior

Make the class `public` or suggest new way to register delivery client with cache (without DI). 

### Test environment

 - .NET 6,  16.0.0-beta5

**Comment by MiroKentico** [comment]
Hi @Enngage,

thanks for finding. We checked this with @gormal (thx for help) and found out, that the problem was probably forgotten update of Wiki. The right approach to create instance of `MemoryCacheManager` in this example is by usage of public factory class `CacheManagerFactory` method `Create`. Please see the updated example in Wiki https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Caching-responses#usage-without-di.

I will also verify, whether there is a need of other update (like to describe usage of this factory more), but this I will do in a future.
